baseURL = "https://olavaga.github.io/boligoppropet/"
languageCode = "nb-no"
title = "Boligoppropet"

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

publishDir = "docs"

defaultContentLanguage = "no"

theme = "hugo-scroll"

[params]
    copyright = "© Olav Aga"

    description = "Felles opprop for en rettferdig boligpolitikk"

    favicon = "images/favico.jpg"

    images = ["images/sentrert-blokk-mot-sky.jpg"]

    title = "Opprop for en rettferdig boligpolitikk"

    [params.meta]
        keywords = "politikk, rettferdighet, bolig, oslo, spire, habitat"
